### ISSUE TITLE
系统安装到zfs文件系统里，双盘raid1，直通用脚本开启有问题

### ISSUE THREAD

**Issue by xxdd239** [ivanhao/pvetools#101]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by davidliyutong** [comment]
On ZFS installations:

1. Modify the `/etc/kernel/cmdline` (assuming you have Intel CPU)

```
root=ZFS=rpool/ROOT/pve-1 boot=zfs intel_iommu=on iommu=pt pcie_acs_override=downstream 
```

2. Add following modules to `/etc/modules`

```
vfio
vfio_iommu_type1
vfio_pci
vfio_virqfd
```

3. Run these commands:

```
update-grub
pve-efiboot-tool refresh
update-initramfs -k all -u
```

4. Finally, reboot
