### ISSUE TITLE
温度显示不全

### ISSUE THREAD

**Issue by jiangliwu** [ivanhao/pvetools#18]
cpu i9 7960x 有一部核心分温度没显示出来
![image](https://user-images.githubusercontent.com/1697481/90488919-2f55e800-e16f-11ea-8b06-9fc92110301b.png)

**Comment by linlunson** [comment]
> 
> 
> cpu i9 7960x 有一部核心分温度没显示出来
> ![image](https://user-images.githubusercontent.com/1697481/90488919-2f55e800-e16f-11ea-8b06-9fc92110301b.png)

啊这是不是炫耀啊哈哈

**Comment by ivanhao** [comment]
已更新
