### ISSUE TITLE
开启“去除订阅提示功能”后，pve频繁死机故障

### ISSUE THREAD

**Issue by zy19941113** [ivanhao/pvetools#23]
用了“去除订阅提示功能”pve每隔两天都会死机，具体症状：
1.pve可以ping通，无法ssh，pve web页面进不去。
2.大部分虚拟机正常运行，部分虚拟机会异常关机。
3.强制重启pve后正常，读取日志，没有发现错误报告.
4.此故障一直反复出现，最长4天出现一次，最短2天出现一次，期间换过内存条，换过散热均未解决，总故障时常超过2个月，。
后来和朋友机器对比，找差异点，发现在关掉pvetools的“去除订阅提示功能”这个功能后，pve已经正常运行超过10天，再也没有出过bug。

**Comment by SamuelZon258** [comment]
我在7.0上尝试去除订阅提示,发现去除不了,然后就关掉了,不过还是三天两头死机一次,网口全亮,pve ping不通,只能强制拔线重启

**Comment by ivanhao** [comment]
增加了修复去除订阅失败的功能。

**Comment by dumganhar** [comment]
> > 我在7.0上尝试去除订阅提示,发现去除不了,然后就关掉了,不过还是三天两头死机一次,网口全亮,pve ping不通,只能强制拔线重启
> 
> apt install --reinstall proxmox-widget-toolkit
> 
> 完事

这是什么原理？为什么重新安装就能解决死机问题？
我的pve也是去除订阅，大概每一个星期会死机一次……

**Comment by HNQX** [comment]
我也出现这个问题了，症状跟阁下完全一致，等回家试一试解决办法

**Comment by liasica** [comment]
我也出现了！

**Comment by vhdapc** [comment]
me too，8.4版本、9.0、9.1版本去除订阅提示后（不管有没有成功），最多两天就会死机（主机网口亮、无法ping通宿主机和虚拟机，openwrt无法工作，只能断电重启），查看日志也没有有效提示，关掉「去除订阅提示」功能后，运行第三天正常
