### ISSUE TITLE
修改界面以显示温度这部分遇到一个问题

### ISSUE THREAD

**Issue by syuraking** [ivanhao/pvetools#24]
ISO的pve-manager版本是6.3-2，我安装好后，运行pvetools修改了界面，
然后使用apt update和apt upgrade升级了pve-manager到了6.3-3，
发现此时界面里没有温度显示了。
运行pvetools，此时工具会提示说已经安装过了，无法修改界面了。

考虑到想重新弄过，就选择删除配置，还原以前的文件，再修改，
结果问题就来了，可能是版本不同，原文件都无法使用了，造成pveproxy无法启动，
reboot后，整个pve都无法正常启动，按pvetools源码排查后，发现就是pve-manager需要的js文件出现问题了

先恢复了旧版本，pve正常后，升级新版本，再用pvetools修改，此时就没有问题出现了。

所以我想麻烦能不能加入一个强制安装选项，直接修改界面，不检查是否有备份文件存在。
谢谢！

**Comment by ivanhao** [comment]
已优化对是否已配置温度显示的判断逻辑。  新版本如果更新pvemanagerlib.js会直接从js判断是否添加，你这种情况，会直接继续进行配置。
