### ISSUE TITLE
Proxmox  7.0正式版出了，请pvetools更新支持一下

### ISSUE THREAD

**Issue by LsnmxNB** [ivanhao/pvetools#31]
https://pve.proxmox.com/wiki/Downloads

**Comment by LsnmxNB** [comment]
@ivanhao  Proxmox 7.0 下pvetools温控显示不能用了，导致ProxmoxWEB面板出很多问题，更换软件源也不能用了，麻烦有空修复一下

**Comment by ivanhao** [comment]
可以测试一下了
