### ISSUE TITLE
添加阿里源后apt-get update提示404

### ISSUE THREAD

**Issue by africa1207** [ivanhao/pvetools#37]
**Describe the bug**
使用工具一键替换功能，替换阿里源或者清华镜像都出现如图错误

**Screenshots**
![image](https://user-images.githubusercontent.com/21698755/148319624-10efde4f-514d-471d-8b21-005f178efd44.png)

**Desktop (please complete the following information):**
 - Version PVE-7.1

**Comment by YYiiEt** [comment]
参考https://mirrors.ustc.edu.cn/help/debian-security.html，安全更新仓库名从发行版代号/updates更新为发行版代号-security，脚本需要维护了。

**Comment by erge6521** [comment]
> **Describe the bug** 使用工具一键替换功能，替换阿里源或者清华镜像都出现如图错误
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/21698755/148319624-10efde4f-514d-471d-8b21-005f178efd44.png)
> 
> **Desktop (please complete the following information):**
> 
> * Version PVE-7.1

换dns为114.114.114.114或者国内任何公共dns

**Comment by 82kg** [comment]
有人解决了吗，我也是这问题

**Comment by 82kg** [comment]
> 参考https://mirrors.ustc.edu.cn/help/debian-security.html ，安全更新仓库名从发行版代号/updates更新为发行版代号-security，脚本需要维护了。

@ivanhao  这脚本还在维护吗

**Comment by ivanhao** [comment]
已处理。
