### ISSUE TITLE
cp: target '/pve-conf/pveConfBackup/20220429/' is not a directory

### ISSUE THREAD

**Issue by xiaoliu2012** [ivanhao/pvetools#41]
cp: target '/pve-conf/pveConfBackup/20220429/' is not a directory
[![LjXf5F.png](https://s1.ax1x.com/2022/04/29/LjXf5F.png)](https://imgtu.com/i/LjXf5F)

**Comment by ivanhao** [comment]
check your path for /pve-conf. if path not exist, use `mkdir /pve-conf` to make the directory manually.
