### ISSUE TITLE
7.2.4本脚本运行后失效不支持温度和频率显示了

### ISSUE THREAD

**Issue by GreatMichaelLee** [ivanhao/pvetools#44]
如题，今天手贱升级了7.2.4,发现无论是跑脚本还是手工改那几个js，7.2.4上面不能显示温度和cpu频率了，7.2.3和以前版本可以，怀疑pve改了前端框架结构。主机上ssh直接sensors命令获取温度什么的都是没问题的，大佬能否研究下？

**Comment by eli6894** [comment]
您好大佬 我想问一下温度频率在哪里看呢

**Comment by ivanhao** [comment]
> 您好大佬 我想问一下温度频率在哪里看呢

在pve节点的概要(summary)
