### ISSUE TITLE
3329行有冲突代码没有解决，脚本错误了

### ISSUE THREAD

**Issue by hanshantao** [ivanhao/pvetools#45]
如题

**Comment by ggtony233** [comment]
雀食 line 3329: syntax error near unexpected token `<<<'

**Comment by overXsky** [comment]
the same
./pvetools.sh: line 3329: syntax error near unexpected token `<<<'
./pvetools.sh: line 3329: `<<<<<<< HEAD'

**Comment by ivanhao** [comment]
resolved.
