### ISSUE TITLE
自动扩展 ROOT 分区插件 autoResize 的原理或源码

### ISSUE THREAD

**Issue by zhangnew** [ivanhao/pvetools#47]
您好，个人认为这是一个高危操作，然后 autoResize 是一个二进制文件，能否提供一个源码，或者一份详细的说明？如何自动？按多少百分比？

**Comment by ivanhao** [comment]
> 您好，个人认为这是一个高危操作，然后 autoResize 是一个二进制文件，能否提供一个源码，或者一份详细的说明？如何自动？按多少百分比？

在wiki里进行了说明，这个使用场景不多，只是针对dd等分区克隆到更大的新硬盘中的场景。

**Comment by zhangnew** [comment]
thx
