### ISSUE TITLE
PVE7.2-3 温度显示功能不生效

### ISSUE THREAD

**Issue by WowRouter** [ivanhao/pvetools#50]
**Describe the bug**
PVE7.2-3 温度显示功能不生效

**Comment by cdunwei** [comment]
PVE7.2.7一样不生效。哈哈。等解决办法。

**Comment by ivanhao** [comment]
清浏览器缓存或更换浏览器试了吗？

**Comment by ivanhao** [comment]
> PVE7.2.7一样不生效。哈哈。等解决办法。

清浏览器缓存或更换浏览器试了吗？

**Comment by ivanhao** [comment]
> **Describe the bug** PVE7.2-3 温度显示功能不生效

经测试可以显示，清浏览器缓存或更换浏览器试一下，同时新版本增加了CPU频率显示。

**Comment by WowRouter** [comment]
感谢大佬，应该是浏览器缓存问题！
