### ISSUE TITLE
CPU省电模式(Powersave)是固定最小CPU频率

### ISSUE THREAD

**Issue by LiHang941** [ivanhao/pvetools#51]
![image](https://user-images.githubusercontent.com/29689440/177714926-6c3bc393-ef0f-4e9d-ac8b-a515674e8a37.png)

**Comment by ivanhao** [comment]
> ![image](https://user-images.githubusercontent.com/29689440/177714926-6c3bc393-ef0f-4e9d-ac8b-a515674e8a37.png)

将在v2.3.1中将powersave改为conservative。

**Comment by 346673164** [comment]
现有8.0.3版本根据步骤输入最大、最小频率后，限制到了最小的频率。有点奇怪
