### ISSUE TITLE
安装web界面温度显示再卸载后web页面打不卡

### ISSUE THREAD

**Issue by kanned1079** [ivanhao/pvetools#53]
安装web界面的温度，传感器显示后，再删除配置后，web控制端打不开，systemctl restart pveproxy.service也不行

PVE版本：v7.2-7
浏览器：chrome
![QQ20220723-173716](https://user-images.githubusercontent.com/58361983/180600198-3eceede1-bb94-45c8-8be8-7502741ba32d.png)

**Comment by mycrazycc** [comment]
我也刚刚出现这个问题，看下了脚本和文件，是那几个文件没有备份成功，/etc/pvetools 这个目录是空的。现在没办法恢复。

**Comment by yhliu-chn** [comment]
Nodes.pm和pvemanagerlib.js没有了，主要是前面那个没有了，把这两个从别的地方复制一下恢复就可以用，删除把这两个文件给干掉了

**Comment by ivanhao** [comment]
问题已修复，安装没成功，Nodes.pm和pvemanagerlib.js没有备份成功，还原的时候删除文件后却没找到备份的原因。

**Comment by Youmio** [comment]
> Nodes.pm和pvemanagerlib.js没有了，主要是前面那个没有了，把这两个从别的地方复制一下恢复就可以用，删除把这两个文件给干掉了

请问这两个文件原本在哪，在哪可以复制下恢复呢？

**Comment by hjnjut** [comment]
我也碰到这个问题了，我的解决办法是，重装pve-manager
apt reinstall pve-manager
然后重启服务
systemctl restart pveproxy
就可以正常显示了
