### ISSUE TITLE
Docker安装报错

### ISSUE THREAD

**Issue by wenpo1975** [ivanhao/pvetools#55]
![3ccdc8d70e251a24feab9d5c8bb1636](https://user-images.githubusercontent.com/24839804/184521531-645b5b09-e06d-4015-b618-178443dbf9e1.png)

显示这个（一闪而过）然后直接跳转引导到安装docker web面板了；
到了安装Docker web面板的时候又提示Docker没安装上
![image](https://user-images.githubusercontent.com/24839804/184521461-87ba0b87-2e40-4d9b-a6dc-f4b269faf65d.png)

看起来说的是镜像源里面没有XX包？但是我从对应的路径进去看是相应的包是存在的；
也尝试通过更换apt镜像但问题依旧
![image](https://user-images.githubusercontent.com/24839804/184521495-e6f97d56-8644-48ca-9ce6-b6a04affe690.png)

**Comment by shiba2046** [comment]
这是因为alpine版本更新后，阿里云源的地址变了。我fork了一个版本解决这个问题，顺便把portainer也改成了ce

[pvetools](https://github.com/shiba2046/pvetools)

#56
