### ISSUE TITLE
开启硬盘休眠，停止pvestatd服务后，会每隔10分钟收到一封邮件提示

### ISSUE THREAD

**Issue by githubzxk** [ivanhao/pvetools#57]
开启硬盘休眠，停止pvestatd服务后，会每隔10分钟收到一封邮件提示：
rm: cannot remove '/var/log/*.gz': No such file or directory
rm: cannot remove '/var/cache/apt/archives/*.deb': No such file or directory
rm: cannot remove '/var/cache/apt/archives/partial/*.deb': No such file or directory
rm: cannot remove '/var/log/*.1': No such file or directory
rm: cannot remove '/var/log/*.2': No such file or directory
rm: cannot remove '/var/log/*.3': No such file or directory
rm: cannot remove '/var/log/*.4': No such file or directory
rm: cannot remove '/var/log/*.5': No such file or directory
rm: cannot remove '/var/log/*.6': No such file or directory
/var/log
/var/log/apt
/var/log/ceph
/var/log/chrony
/var/log/corosync
/var/log/glusterfs
/var/log/journal
/var/log/journal/54016a6cb3cf42c7914c113c9a43403d
/var/log/lxc
/var/log/private
/var/log/pve
/var/log/pve/tasks
/var/log/pve/tasks/0
/var/log/pve/tasks/1
/var/log/pve/tasks/2
/var/log/pve/tasks/3
/var/log/pve/tasks/4
/var/log/pve/tasks/5
/var/log/pve/tasks/6
/var/log/pve/tasks/7
/var/log/pve/tasks/8
/var/log/pve/tasks/9
/var/log/pve/tasks/A
/var/log/pve/tasks/B
/var/log/pve/tasks/C
/var/log/pve/tasks/D
/var/log/pve/tasks/E
/var/log/pve/tasks/F
/var/log/pveproxy
/var/log/runit
/var/log/runit/ssh
/var/log/samba
/var/log/samba/cores
/var/log/samba/cores/nmbd
/var/log/samba/cores/smbd
/var/log/vzdump

关掉硬盘休眠和开启pvestatd服务后仍旧会受到邮件

**Comment by ivanhao** [comment]
> 
你这个不是因为开启硬盘休眠，是因为开了usb设备做为系统盘的优化。把这个关了就可以
