### ISSUE TITLE
您的Proxmox VE版本不支持此方式！

### ISSUE THREAD

**Issue by babyvox550** [ivanhao/pvetools#65]
![image](https://user-images.githubusercontent.com/13328183/204118588-8868ce4f-97ad-4423-b8c6-2fa1de8a9f6a.png)
![image](https://user-images.githubusercontent.com/13328183/204118747-611441e2-2d35-48f7-8d4e-707c91601d76.png)

![image](https://user-images.githubusercontent.com/13328183/204118597-47c2cf1e-8e17-494d-b8c6-52fca3748e02.png)
![image](https://user-images.githubusercontent.com/13328183/204118713-3dbdb653-3a28-4a94-87bb-3a8c89d665a1.png)
pve版本如上。
显示不支持。

**Comment by babyvox550** [comment]
![image](https://user-images.githubusercontent.com/13328183/204122772-dcab0693-cd9f-4efc-9089-44cb8233657a.png)
升级到7.3还是一样的问题

**Comment by ivanhao** [comment]
/usr/share/pve-manager/js/pvemanagerlib.js
/usr/share/perl5/PVE/API2/Nodes.pm
请检查一下这两个文件是否存在，这个报错是因为未检测到这两个文件。
