### ISSUE TITLE
PVE 8.0 ”配置pve的web界面显示传感器温度、CPU频率“功能异常。

### ISSUE THREAD

**Issue by hsj1992** [ivanhao/pvetools#84]
CPU实时频率显示异常：

CPU频率 CPU实时(Cur): undefined MHz \| 最小(min): 800.0000 MHz \| 最大(max): 2900.0000 MHz
--
 
Sensors Data:
Packageid0 +46.0°C | Core0 +46.0°C
Core1 +48.0°C | Core2 +48.0°C
Core3 +48.0°C

**Comment by Sincejunly** [comment]
我加了以后一直loading

**Comment by christinkaka** [comment]
#85 等大佬合并。。。
