### ISSUE TITLE
配置apt国内源、安装配置VIM可导致原配置文件被覆盖

### ISSUE THREAD

**Issue by nostopp** [ivanhao/pvetools#90]
以修改更新源为例，目前配置更换更新源时是直接 cp /etc/apt/sources.list /etc/apt/sources.list.bak,
若配置阿里源后不还原配置就直接配置ustc源将导致原本文件被覆盖.
配置vim也是同理会导致原配置被覆盖.

**Comment by ivanhao** [comment]
最新版本已处理
