### ISSUE TITLE
安装配置温度、CPU频率显示之后，如果删除配置，pve概要就会一直在载入中，无法正常显示，重启也没有用

### ISSUE THREAD

**Issue by EricCorleone** [ivanhao/pvetools#95]
安装配置温度、CPU频率显示之后，如果删除配置，pve概要就会一直在载入中，无法正常显示，重启也没有用：
![image](https://github.com/ivanhao/pvetools/assets/55615178/7d43aa1f-5b29-40f8-b71b-79c070f8daf3)

**Comment by EricCorleone** [comment]
![image](https://github.com/ivanhao/pvetools/assets/55615178/51c9b901-bb9f-4cb3-acae-692028a35219)

**Comment by EricCorleone** [comment]
我又用虚拟机装了个PVE，把`/usr/share/pve-manager/js/pvemanagerlib.js`和`/usr/share/perl5/PVE/API2/Nodes.pm`两个文件复制过来覆盖了就好了，应该是脚本在安装该功能的时候没有备份这两个文件，导致我删除配置的时候这两个文件没有恢复。

**Comment by AoThen** [comment]
确实，没看到有备份文件，脚本没成功备份这2个

**Comment by sui-mu** [comment]
> 我又用虚拟机装了个PVE，把`/usr/share/pve-manager/js/pvemanagerlib.js`和`/usr/share/perl5/PVE/API2/Nodes.pm`两个文件复制过来覆盖了就好了，应该是脚本在安装该功能的时候没有备份这两个文件，导致我删除配置的时候这两个文件没有恢复。

能分享一下这两个文件吗

**Comment by ivanhao** [comment]
apt install --reinstall pvemanager && systemctl restart pveproxy
可以修复，最新版本已增加，用还原配置就可以修复，记得修复完全要清理浏览器缓存

**Comment by AndyEverLie** [comment]
> apt install --reinstall pvemanager && systemctl restart pveproxy 可以修复，最新版本已增加，用还原配置就可以修复，记得修复完全要清理浏览器缓存

无语，按你上面的命令是失败的，其中 pvemanager 改成正确的 pve-manager 也不行，
Reinstallation of pve-manager is not possible, it cannot be downloaded.

卸载时就不能还原改动就好了吗？不能还原成原来的样子，就不要随便发出来啊


----

![Screenshot 2024-02-25 at 11 54 23 PM](https://github.com/ivanhao/pvetools/assets/1732165/e83282f6-1106-458c-a801-18d5a1c25934)

把 /usr/share/pve-manager/js/pvemanagerlib.js 文件里这几句注释掉就正常了。
